### ISSUE TITLE
MySQL - Localhost error

### ISSUE THREAD

**Issue by akimfromparis** [lllzzy/wechat_article_spider#1]
Hello lllzy,

Thank you for the script. I got a local host error. 
Thx!

![error-wechat](https://user-images.githubusercontent.com/58808904/99392213-a3716a80-28db-11eb-9ab3-c9b037f0b64d.jpg)

**Comment by lllzzy** [comment]
你的 MySQL 配置可能有问题，你的mysql服务拒绝了访问。写一个单独的pymysql连接mysql的测试。



---Original---
